name: Clean Conf Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clean-conf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run cleaning script
      run: python scripts/remove_comments_conf.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit stripped files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add stripped_files/*
        git commit -m "Add stripped .conf files" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
